//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xin.WebApplication.NAQRPDService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AQRPD", Namespace="http://schemas.datacontract.org/2004/07/NAQRPD.Common")]
    [System.SerializableAttribute()]
    public partial class AQRPD : Xin.WebApplication.NAQRPDService.HourAQICalculate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HourAQICalculate", Namespace="http://schemas.datacontract.org/2004/07/NAQRPD.Common.Evaluation")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Xin.WebApplication.NAQRPDService.AQRPD))]
    public partial class HourAQICalculate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AQIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> COField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> O3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PM10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PM25Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryPollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AQI {
            get {
                return this.AQIField;
            }
            set {
                if ((this.AQIField.Equals(value) != true)) {
                    this.AQIField = value;
                    this.RaisePropertyChanged("AQI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CO {
            get {
                return this.COField;
            }
            set {
                if ((this.COField.Equals(value) != true)) {
                    this.COField = value;
                    this.RaisePropertyChanged("CO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NO2 {
            get {
                return this.NO2Field;
            }
            set {
                if ((this.NO2Field.Equals(value) != true)) {
                    this.NO2Field = value;
                    this.RaisePropertyChanged("NO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> O3 {
            get {
                return this.O3Field;
            }
            set {
                if ((this.O3Field.Equals(value) != true)) {
                    this.O3Field = value;
                    this.RaisePropertyChanged("O3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PM10 {
            get {
                return this.PM10Field;
            }
            set {
                if ((this.PM10Field.Equals(value) != true)) {
                    this.PM10Field = value;
                    this.RaisePropertyChanged("PM10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PM25 {
            get {
                return this.PM25Field;
            }
            set {
                if ((this.PM25Field.Equals(value) != true)) {
                    this.PM25Field = value;
                    this.RaisePropertyChanged("PM25");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryPollutant {
            get {
                return this.PrimaryPollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPollutantField, value) != true)) {
                    this.PrimaryPollutantField = value;
                    this.RaisePropertyChanged("PrimaryPollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SO2 {
            get {
                return this.SO2Field;
            }
            set {
                if ((this.SO2Field.Equals(value) != true)) {
                    this.SO2Field = value;
                    this.RaisePropertyChanged("SO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AQDPD", Namespace="http://schemas.datacontract.org/2004/07/NAQRPD.Common")]
    [System.SerializableAttribute()]
    public partial class AQDPD : Xin.WebApplication.NAQRPDService.DayAQICalculate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DayAQICalculate", Namespace="http://schemas.datacontract.org/2004/07/NAQRPD.Common.Evaluation")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Xin.WebApplication.NAQRPDService.AQDPD))]
    public partial class DayAQICalculate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AQIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> COField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> O3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PM10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PM25Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryPollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AQI {
            get {
                return this.AQIField;
            }
            set {
                if ((this.AQIField.Equals(value) != true)) {
                    this.AQIField = value;
                    this.RaisePropertyChanged("AQI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CO {
            get {
                return this.COField;
            }
            set {
                if ((this.COField.Equals(value) != true)) {
                    this.COField = value;
                    this.RaisePropertyChanged("CO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NO2 {
            get {
                return this.NO2Field;
            }
            set {
                if ((this.NO2Field.Equals(value) != true)) {
                    this.NO2Field = value;
                    this.RaisePropertyChanged("NO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> O3 {
            get {
                return this.O3Field;
            }
            set {
                if ((this.O3Field.Equals(value) != true)) {
                    this.O3Field = value;
                    this.RaisePropertyChanged("O3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PM10 {
            get {
                return this.PM10Field;
            }
            set {
                if ((this.PM10Field.Equals(value) != true)) {
                    this.PM10Field = value;
                    this.RaisePropertyChanged("PM10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PM25 {
            get {
                return this.PM25Field;
            }
            set {
                if ((this.PM25Field.Equals(value) != true)) {
                    this.PM25Field = value;
                    this.RaisePropertyChanged("PM25");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryPollutant {
            get {
                return this.PrimaryPollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPollutantField, value) != true)) {
                    this.PrimaryPollutantField = value;
                    this.RaisePropertyChanged("PrimaryPollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SO2 {
            get {
                return this.SO2Field;
            }
            set {
                if ((this.SO2Field.Equals(value) != true)) {
                    this.SO2Field = value;
                    this.RaisePropertyChanged("SO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NAQRPDService.INAQRPDService")]
    public interface INAQRPDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQRPSDLive", ReplyAction="http://tempuri.org/INAQRPDService/GetAQRPSDLiveResponse")]
        Xin.WebApplication.NAQRPDService.AQRPD[] GetAQRPSDLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQRPSDLive", ReplyAction="http://tempuri.org/INAQRPDService/GetAQRPSDLiveResponse")]
        System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQRPD[]> GetAQRPSDLiveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQSPSDLive", ReplyAction="http://tempuri.org/INAQRPDService/GetAQSPSDLiveResponse")]
        Xin.WebApplication.NAQRPDService.AQDPD[] GetAQSPSDLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQSPSDLive", ReplyAction="http://tempuri.org/INAQRPDService/GetAQSPSDLiveResponse")]
        System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQDPD[]> GetAQSPSDLiveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQRPSDHistory", ReplyAction="http://tempuri.org/INAQRPDService/GetAQRPSDHistoryResponse")]
        Xin.WebApplication.NAQRPDService.AQRPD[] GetAQRPSDHistory(System.DateTime beginTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQRPSDHistory", ReplyAction="http://tempuri.org/INAQRPDService/GetAQRPSDHistoryResponse")]
        System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQRPD[]> GetAQRPSDHistoryAsync(System.DateTime beginTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQDPSDLive", ReplyAction="http://tempuri.org/INAQRPDService/GetAQDPSDLiveResponse")]
        Xin.WebApplication.NAQRPDService.AQDPD[] GetAQDPSDLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQDPSDLive", ReplyAction="http://tempuri.org/INAQRPDService/GetAQDPSDLiveResponse")]
        System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQDPD[]> GetAQDPSDLiveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQDPSDHistory", ReplyAction="http://tempuri.org/INAQRPDService/GetAQDPSDHistoryResponse")]
        Xin.WebApplication.NAQRPDService.AQDPD[] GetAQDPSDHistory(System.DateTime beginTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQDPSDHistory", ReplyAction="http://tempuri.org/INAQRPDService/GetAQDPSDHistoryResponse")]
        System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQDPD[]> GetAQDPSDHistoryAsync(System.DateTime beginTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQRPCDLive", ReplyAction="http://tempuri.org/INAQRPDService/GetAQRPCDLiveResponse")]
        Xin.WebApplication.NAQRPDService.AQRPD[] GetAQRPCDLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQRPCDLive", ReplyAction="http://tempuri.org/INAQRPDService/GetAQRPCDLiveResponse")]
        System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQRPD[]> GetAQRPCDLiveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQRPCDHistory", ReplyAction="http://tempuri.org/INAQRPDService/GetAQRPCDHistoryResponse")]
        Xin.WebApplication.NAQRPDService.AQRPD[] GetAQRPCDHistory(System.DateTime beginTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQRPCDHistory", ReplyAction="http://tempuri.org/INAQRPDService/GetAQRPCDHistoryResponse")]
        System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQRPD[]> GetAQRPCDHistoryAsync(System.DateTime beginTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQDPCDLive", ReplyAction="http://tempuri.org/INAQRPDService/GetAQDPCDLiveResponse")]
        Xin.WebApplication.NAQRPDService.AQDPD[] GetAQDPCDLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQDPCDLive", ReplyAction="http://tempuri.org/INAQRPDService/GetAQDPCDLiveResponse")]
        System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQDPD[]> GetAQDPCDLiveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQDPCDHistory", ReplyAction="http://tempuri.org/INAQRPDService/GetAQDPCDHistoryResponse")]
        Xin.WebApplication.NAQRPDService.AQDPD[] GetAQDPCDHistory(System.DateTime beginTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAQRPDService/GetAQDPCDHistory", ReplyAction="http://tempuri.org/INAQRPDService/GetAQDPCDHistoryResponse")]
        System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQDPD[]> GetAQDPCDHistoryAsync(System.DateTime beginTime, System.DateTime endTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INAQRPDServiceChannel : Xin.WebApplication.NAQRPDService.INAQRPDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NAQRPDServiceClient : System.ServiceModel.ClientBase<Xin.WebApplication.NAQRPDService.INAQRPDService>, Xin.WebApplication.NAQRPDService.INAQRPDService {
        
        public NAQRPDServiceClient() {
        }
        
        public NAQRPDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NAQRPDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NAQRPDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NAQRPDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Xin.WebApplication.NAQRPDService.AQRPD[] GetAQRPSDLive() {
            return base.Channel.GetAQRPSDLive();
        }
        
        public System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQRPD[]> GetAQRPSDLiveAsync() {
            return base.Channel.GetAQRPSDLiveAsync();
        }
        
        public Xin.WebApplication.NAQRPDService.AQDPD[] GetAQSPSDLive() {
            return base.Channel.GetAQSPSDLive();
        }
        
        public System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQDPD[]> GetAQSPSDLiveAsync() {
            return base.Channel.GetAQSPSDLiveAsync();
        }
        
        public Xin.WebApplication.NAQRPDService.AQRPD[] GetAQRPSDHistory(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.GetAQRPSDHistory(beginTime, endTime);
        }
        
        public System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQRPD[]> GetAQRPSDHistoryAsync(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.GetAQRPSDHistoryAsync(beginTime, endTime);
        }
        
        public Xin.WebApplication.NAQRPDService.AQDPD[] GetAQDPSDLive() {
            return base.Channel.GetAQDPSDLive();
        }
        
        public System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQDPD[]> GetAQDPSDLiveAsync() {
            return base.Channel.GetAQDPSDLiveAsync();
        }
        
        public Xin.WebApplication.NAQRPDService.AQDPD[] GetAQDPSDHistory(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.GetAQDPSDHistory(beginTime, endTime);
        }
        
        public System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQDPD[]> GetAQDPSDHistoryAsync(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.GetAQDPSDHistoryAsync(beginTime, endTime);
        }
        
        public Xin.WebApplication.NAQRPDService.AQRPD[] GetAQRPCDLive() {
            return base.Channel.GetAQRPCDLive();
        }
        
        public System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQRPD[]> GetAQRPCDLiveAsync() {
            return base.Channel.GetAQRPCDLiveAsync();
        }
        
        public Xin.WebApplication.NAQRPDService.AQRPD[] GetAQRPCDHistory(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.GetAQRPCDHistory(beginTime, endTime);
        }
        
        public System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQRPD[]> GetAQRPCDHistoryAsync(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.GetAQRPCDHistoryAsync(beginTime, endTime);
        }
        
        public Xin.WebApplication.NAQRPDService.AQDPD[] GetAQDPCDLive() {
            return base.Channel.GetAQDPCDLive();
        }
        
        public System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQDPD[]> GetAQDPCDLiveAsync() {
            return base.Channel.GetAQDPCDLiveAsync();
        }
        
        public Xin.WebApplication.NAQRPDService.AQDPD[] GetAQDPCDHistory(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.GetAQDPCDHistory(beginTime, endTime);
        }
        
        public System.Threading.Tasks.Task<Xin.WebApplication.NAQRPDService.AQDPD[]> GetAQDPCDHistoryAsync(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.GetAQDPCDHistoryAsync(beginTime, endTime);
        }
    }
}
